apiVersion: v1
kind: Secret
metadata:
  name: personal-project-manager-env
type: Opaque
stringData:
  FIREBASE_API_KEY: your-web-api-key
  FIREBASE_AUTH_DOMAIN: your-project-id.firebaseapp.com
  FIREBASE_PROJECT_ID: your-project-id
  FIREBASE_STORAGE_BUCKET: your-project-id.firebasestorage.app
  FIREBASE_MESSAGING_SENDER_ID: your-messaging-sender-id
  FIREBASE_APP_ID: your-app-id

